### ISSUE TITLE
DNSimple API authentication

### ISSUE THREAD

**Issue by billmoritz** [dnsimple/chef-dnsimple#24]
The username / password method of authentication used by this cookbook will log you out of the console.  If you have many servers using this cookbook it renders the https://dnsimple.com web ui completely useless.  After contacting support over there they applied a temp fix and suggested that I switch to the token authentication.  

Maybe we should switch from Fog to https://github.com/aetrion/dnsimple-ruby#api-token

**Comment by martinisoft** [comment]
Hi @billmoritz 

Sorry for the late reply here. We are planning to make 2.0 of this cookbook use the soon to be released dnsimple-ruby gem 2.0 which drops the need for the fog gem. In fact, the current fog gem conflicts with the latest Chef release so you cannot use 12.1.0 with this cookbook right now due to that dependency problem.

**Comment by patcon** [comment]
bump. Any update on v2 of the cookbook?

**Comment by martinisoft** [comment]
@patcon For the update I think we'll look at merging either #28 or #29 to get this shipped before we look at a 2.0 release. Sorry about the long wait on an answer here.

**Comment by weppos** [comment]
@martinisoft I see both #28 and #29 are focused on using Fog. I suggest we should switch to our Ruby client, as it is definitely more flexible than Fog. Moreover, we have better control over the release cycle.

That will be increasingly more important once we'll release API v2.

**Comment by martinisoft** [comment]
@weppos That is a fair point. I'll look at whipping up a pull request.
