### ISSUE TITLE
Running integration tests with custom domain fails

### ISSUE THREAD

**Issue by russellseymour** [dnsimple/chef-dnsimple#52]
Whilst getting the new CPCP platform up and running I have been working on getting the cookbooks working properly.

I have got the dnsimple cookbook almost working, but it is failing on the last test.

I have registered the domain `dnsimple.cpcp.chef.xyz` in my Dnsimple Sandbox. All the tests for creating and deleting records work - however when the test for updating a record is performed it fails. This is because it is testing for the string `testing.dnsimple.xyz`.

The error is

```
Profile: Update Zone Record Test (update_record)
Version: 1.0.0
Target:  ssh://azure@40.71.94.119:22


  zone record
     ���  lookup on dnsimple.cpcp.chef.xyz for cnamerecord content should eq "testing.dnsimple.xyz"
     
     expected: "testing.dnsimple.xyz"
          got: "testing.dnsimple.cpcp.chef.xyz"
     
     (compared using ==)
     
     ���  lookup on dnsimple.cpcp.chef.xyz for cnamerecord ttl should eq 60

Test Summary: 1 successful, 1 failure, 0 skipped
```

Full output for the latest build can be found here - https://cpcp.chef.io/job/dnsimple-cookbook/17/console

**Comment by martinisoft** [comment]
Hey there @russellseymour I know we spoke about this a while back and it got lost in the shuffle of work. I've got a quick bugfix in mind that should resolve this issue for the CPCP builder. Once this issue is marked as resolved please re-test and let us know if it's fixed for you. If not, re-open the issue with a fresh set of output data.
